language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
install: npm install
before_script: npm run dist
script: npm test
before_deploy: echo 'All unit tests passed; Successfully built distribution assets;
  Preparing to deploy Staff Picks to AWS'
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$aws_access_key_id_production"
  secret_access_key: "$aws_secret_access_key_production"
  region: us-east-1
  app: "$aws_app_name"
  env: "$aws_environment_name_production"
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: "$aws_app_name"
  on:
    repo: NYPL/dgx-global-search
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$aws_access_key_id_production"
  secret_access_key: "$aws_secret_access_key_production"
  region: us-east-1
  app: "$aws_app_name"
  env: "$aws_environment_name_qa"
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: "$aws_app_name"
  on:
    repo: NYPL/dgx-global-search
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$aws_access_key_id_development"
  secret_access_key: "$aws_secret_access_key_development"
  region: us-east-1
  app: "$aws_app_name"
  env: "$aws_environment_name_development"
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: "$aws_app_name"
  on:
    repo: NYPL/dgx-global-search
    branch: deploy-eb
after_deploy: echo 'Successfully executed deploy trigger for Staff Picks on AWS'
env:
  global:
    secure: gc8cPguG/dRpOjc6kPAwggDFv+pLG/nOgOkEtgmAYWHlRC89IgXNsTCsl7IRwQzWAkpyQryZLnWn6eOiLgedDu0nBbFUFsERBykm12JOvqMT9vsxyumvsoDwwGQzEpeuCedEJ4jPMvHpgjju2M2bQEMK7ReaTDRdYbcoJ8pM0L6UaXwFKeLdoMoRf6JKhYImy9RsuU2fUt8q/9s4YpYQaSGqQH0X9bEqdXZNIuSbeKvXjk6r6WQnfp0Ek5m1qy4f7Kz+J/3ifgZ144CptFPrYuBq/f/HuzyC+8qHTV0VbI03h6l9F0I9jPEW0Y5I07M1Zpe9duHjD/x7RTSfzXIhE9+qT6gQ6m6MUIFpzAHB7cyhpMoc8mwdUf9gEZexk0CXZq2UK/CPgI9d0IjKjJYnqlD/TsiQ2uAW2n3HkMM/uia15Xoal3tq+4Xw2GQlPoCMon9xnXMNSuCUKUqupE2gHlyDQq8Kmy16FRoRjjk1XX6I3Iemdr1ZRImV8YVsnSiBsl4dLY72lo2isCF5HzOXlA9vmUk3ZbtIUieoG8Olp8bv9N6UKc3B7WpGuLrrV20py3pxEIyv/GLYz/eDLihcDjPxMwzyMWA7IdbQVXYht6jAMjCXI5GzzuGvEWjXxUxgXK0+Pu6X545CPe9J5HGIOjjbcL44aBgvXb3cKLPZJY8=
